1
# Codemagic CI/CD configuration for Aziz Graphics Android Project
2

3
workflows:
4
  android-build:
5
    name: Android Build and Sign
6
    instance_type: mac_mini_m1
7
    
8
    environment:
9
      # Set the Java version
10
      java: 17
11
      # Set the Android SDK version
12
      android_sdk_version: 34  # Correct key for SDK version
13
      # Define environment variables for signing credentials
14
      # These variables must be set in Codemagic UI (Environment Variables tab)
15
      groups:
16
        - android-signing-credentials # User must create this group and add the variables below
17
      vars:
18
        # Keystore file name (must be uploaded to Codemagic)
19
        CM_KEYSTORE_PATH: aziz_graphics.jks
20
        # Keystore passwords and key alias from signing.properties
21
        CM_KEYSTORE_PASSWORD: aziz_store_pass
22
        CM_KEY_ALIAS: aziz_graphics_key
23
        CM_KEY_PASSWORD: aziz_key_pass
24

25
    scripts:
26
      - name: Set up local properties
27
        script: |
28
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
29
      
30
      - name: Get dependencies
31
        script: |
32
          ./gradlew dependencies
33
          
34
      - name: Build Android Release APK
35
        script: |
36
          # The build command uses the signing configuration defined in app/build.gradle
37
          ./gradlew assembleRelease
38

39
    artifacts:
40
      - app/build/outputs/apk/release/*.apk
41
      
42
    publishing:
43
      # Example of publishing to Google Play. User needs to configure this in Codemagic UI.
44
      # google_play:
45
      #   track: internal
46
      #   service_account_key: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
47
      #   submit_as_draft: true
48
      
49
      # Publish to Codemagic for download
50
      email:
51
        recipients:
52
          - user.email@example.com # Replace with your email
53
        notify:
54
          success: true
55
          failure: true
56
