# Codemagic CI/CD configuration for Aziz Graphics Android Project

workflows:
  android-build:
    name: Android Build and Sign
    instance_type: mac_mini_m1
    
    environment:
      # Set the Java version
      java: 17
      # Set the Android SDK version
     
      android_sdk: 34
      # Define environment variables for signing credentials
      # These variables must be set in Codemagic UI (Environment Variables tab)
      groups:
        - android-signing-credentials # User must create this group and add the variables below
      vars:
        # Keystore file name (must be uploaded to Codemagic)
        CM_KEYSTORE_PATH: aziz_graphics.jks
        # Keystore passwords and key alias from signing.properties
        CM_KEYSTORE_PASSWORD: aziz_store_pass
        CM_KEY_ALIAS: aziz_graphics_key
        CM_KEY_PASSWORD: aziz_key_pass

    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Get dependencies
        script: |
          ./gradlew dependencies
          
      - name: Build Android Release APK
        script: |
          # The build command uses the signing configuration defined in app/build.gradle
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/apk/release/*.apk
      
    publishing:
      # Example of publishing to Google Play. User needs to configure this in Codemagic UI.
      # google_play:
      #   track: internal
      #   service_account_key: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   submit_as_draft: true
      
      # Publish to Codemagic for download
      email:
        recipients:
          - user.email@example.com # Replace with your email
        notify:
          success: true
          failure: true
